cors:
  originPatterns: http://localhost:8080,http://localhost:3000

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_rest
    username: root
    password: 1123581321asG!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  pathsToMatch:
    - /api/**
    - /auth/**
  swagger-ui:
    use-root-path: true

  application:
    name: DemoApplication